---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: devbox
  labels:
    app.kubernetes.io/name: devbox
    app.kubernetes.io/instance: devbox
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app.kubernetes.io/name: devbox
      app.kubernetes.io/instance: devbox
  template:
    metadata:
      labels:
        app.kubernetes.io/name: devbox
        app.kubernetes.io/instance: devbox
    spec:
      imagePullSecrets:
        []
      securityContext:
        fsGroup: 1000
      initContainers:
      - name: init-chmod-data
        image: "andrewkaczynski/devbox:1.3"
        imagePullPolicy: IfNotPresent
        command:
          - sh
          - -c
          - |
            if [ ! -d /home/coder/data ]; then mkdir /home/coder/data; fi &&
            chown -R 1000:1000 /home/coder
        securityContext:
          runAsUser: 0
        volumeMounts:
        - name: data
          mountPath: /home/coder/data
      containers:
        - name: devbox
          image: "andrewkaczynski/devbox:1.3"
          imagePullPolicy: Always
          securityContext:
            runAsUser: 1000
          env:
          - name: PASSWORD
            valueFrom:
              secretKeyRef:
                name: devbox
                key: password
          volumeMounts:
          - name: data
            mountPath: /home/coder/data
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /
              port: http
          readinessProbe:
            httpGet:
              path: /
              port: http
          resources:
            {}
      serviceAccountName: devbox
      volumes:
      - name: data
        persistentVolumeClaim:
          claimName: devbox