---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: devbox
  labels:
    app.kubernetes.io/name: devbox
    app.kubernetes.io/instance: devbox
spec:
  accessModes:
    - "ReadWriteOnce"
  resources:
    requests:
      storage: "10Gi"